name: pickled_cucumber CI
on: push

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    lib-test:
        name: Run library tests
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
            - uses: dart-lang/setup-dart@v1

            - run: |
                dart pub get
                dart format --set-exit-if-changed .
                dart analyze
                dart test
    dart-example:
        needs: lib-test
        name: Run dart example
        runs-on: ubuntu-latest
        
        steps:
            - uses: actions/checkout@v5
            - uses: dart-lang/setup-dart@v1
            
            - name: Run dart example tests
              working-directory: example
              run: |
                dart pub get
                dart format --set-exit-if-changed .
                dart analyze
                dart test
    dart-frog-example:
        needs: dart-example
        name: Run dart frog example
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v5
            - uses: dart-lang/setup-dart@v1

            - name: Run dart frog example tests
              working-directory: dart_frog_example
              run: |
                dart pub global activate dart_frog_cli
                dart pub get
                dart format --set-exit-if-changed .
                dart analyze
                dart test
    flutter-example:
        needs: dart-example
        name: Run flutter example
        runs-on: ubuntu-latest
        
        steps:
            - uses: actions/checkout@v5
            - uses: subosito/flutter-action@v2
              with:
                cache: true
            
            - name: Run flutter example tests
              working-directory: flutter_example
              run: |
                flutter pub get
                dart run build_runner build --delete-conflicting-outputs
                dart format --set-exit-if-changed .
                flutter analyze
                flutter test

